test_that("TimesFM spike matches the pinned official transformer block", {
  skip_if_not_installed("torch")
  skip_if_not(torch::torch_is_installed(), "LibTorch is not installed")

  module <- timesfm_spike_module()
  timesfm_spike_fill_reference_weights(module)
  input <- torch::torch_tensor(c(
    0.2, -0.1, 0.4, 0.3,
    0.5, 0.7, -0.2, 0.1,
    -0.4, 0.6, 0.8, -0.3
  ))$reshape(c(1, 3, 4))
  mask <- torch::torch_tensor(
    matrix(c(FALSE, FALSE, FALSE), nrow = 1),
    dtype = torch::torch_bool()
  )
  output <- module(input, mask)

  expect_identical(output$embeddings$shape, c(1L, 3L, 4L))
  expect_identical(output$quantiles$shape, c(1L, 3L, 3L, 3L))

  # Generated by .agents/generate-timesfm-spike-reference.py from upstream
  # google-research/timesfm commit 3dae50b20d7a724981e8ea36cda75578f80dd2dc.
  expected_embeddings <- c(
    0.5827177763, 0.4629762769, -0.6941000223, 1.1751779318,
    1.7553013563, 0.8403856754, -1.6186712980, 1.8144954443,
    -0.5810703039, 0.5694165230, 1.0482556820, -0.6246939898
  )
  expected_quantiles <- c(
    -0.0025582565, -0.0009701217, 0.0038264908,
    -0.0040322002, 0.0014447474, 0.0021434946,
    -0.0042469115, 0.0034084425, -0.0002088952,
    0.0511113293, -0.0577520691, 0.0243872162,
    0.0258709751, -0.0582080148, 0.0502236299,
    -0.0074486816, -0.0404860489, 0.0603755824,
    0.0039441814, 0.0483309627, -0.0671266466,
    0.0394228362, 0.0155896759, -0.0598030239,
    0.0625900477, -0.0220201518, -0.0338033848
  )
  expected_embeddings <- torch::torch_tensor(expected_embeddings)$reshape(c(1, 3, 4))
  expected_quantiles <- torch::torch_tensor(expected_quantiles)$reshape(c(1, 3, 3, 3))
  expect_lt(max(abs(as.numeric(output$embeddings - expected_embeddings))), 1e-6)
  expect_lt(max(abs(as.numeric(output$quantiles - expected_quantiles))), 1e-6)
})

test_that("fused QKV loading preserves the upstream out-by-in layout", {
  skip_if_not_installed("torch")
  skip_if_not(torch::torch_is_installed(), "LibTorch is not installed")

  module <- timesfm_spike_module()
  weight <- timesfm_spike_tensor(c(12, 4), 42)
  timesfm_spike_load_fused_qkv(module, weight)
  expect_equal(
    as.numeric(module$transformer$attn$qkv_proj$weight),
    as.numeric(weight)
  )
  expect_error(
    timesfm_spike_load_fused_qkv(module, torch::torch_zeros(c(4, 12))),
    "Fused QKV must have shape"
  )
})
